"""
NMB HQ Monthly Billing — Custom Field Creation Script (v3 — orphan support)
============================================================================

Creates 6 custom fields needed by the monthly billing report:

  3 fields supporting the MREQ-driven flow (Phase 1):
    - Material Request Item.custom_quoted_in_quotation
    - Quotation Item.custom_approved_requisition_no
    - Quotation Item.custom_source_mreq_item

  3 fields supporting orphan cost reconciliation (Phase 2 / Option 2):
    - Purchase Invoice Item.custom_billed_in_quotation
    - Stock Entry Detail.custom_billed_in_quotation
    - Expense Claim.custom_billed_in_quotation

DESIGN NOTE:
    The 3 new "billed_in_quotation" fields enable the report to surface
    PINV / STE / EXP rows that exist on the project but have no MREQ link.
    Once such an orphan row is included in a generated Quotation, the
    field is stamped — so it disappears from subsequent report runs and
    cannot be double-billed.

    EXP Claims are billed at claim level (lump-sum), so the field lives
    on the Expense Claim header. PINV/STE are billed line-by-line, so
    the field lives on the child tables.

Idempotent: safe to run multiple times. Existing fields are skipped.

USAGE (Frappe Cloud — no bench console):
    Create the 3 fields manually via Customize Form UI.
    Spec for each field is in the FIELDS list below.

USAGE (self-hosted bench):
    bench --site <your-site> console
    >>> exec(open('/path/to/create_billing_fields.py').read())
    >>> create_all()

ROLLBACK:
    >>> remove_all()
"""

import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_field


# Fields are (doctype, fieldname, properties) tuples.
# All 3 are hidden by default — they are tracking/audit fields, not data-entry.
FIELDS = [
    # --- Material Request Item (1 field) ---
    (
        "Material Request Item",
        "custom_quoted_in_quotation",
        {
            "label": "Quoted In Quotation",
            "fieldtype": "Link",
            "options": "Quotation",
            "insert_after": "rate",
            "read_only": 1,
            "hidden": 1,
            "no_copy": 1,
            "description": "Set automatically when this MREQ line is included in a Quotation generated by the NMB HQ Monthly Billing report. Used to filter 'Hide already-quoted' lines and prevent double-quoting.",
        },
    ),
    # --- Quotation Item (2 fields) ---
    (
        "Quotation Item",
        "custom_approved_requisition_no",
        {
            "label": "Approved Requisition No.",
            "fieldtype": "Data",
            "insert_after": "item_name",
            "hidden": 1,
            "description": "NMB Purchase Requisition number — carried from the source MREQ for audit trail. Set automatically by Generate Quotation flow.",
        },
    ),
    (
        "Quotation Item",
        "custom_source_mreq_item",
        {
            "label": "Source MREQ Item",
            "fieldtype": "Data",
            "insert_after": "custom_approved_requisition_no",
            "read_only": 1,
            "hidden": 1,
            "no_copy": 1,
            "description": "Reference back to the originating Material Request Item (format: MREQ-NNNNN row-name). Set automatically; do not edit.",
        },
    ),
    # --- Purchase Invoice Item (1 field — Phase 2 orphan support) ---
    (
        "Purchase Invoice Item",
        "custom_billed_in_quotation",
        {
            "label": "Billed In Quotation",
            "fieldtype": "Link",
            "options": "Quotation",
            "insert_after": "rate",
            "read_only": 1,
            "hidden": 1,
            "no_copy": 1,
            "description": "Set automatically when this PINV line is included in a Quotation generated by the NMB HQ Monthly Billing report. Used to filter orphan PINV rows that have already been billed.",
        },
    ),
    # --- Stock Entry Detail (1 field — Phase 2 orphan support) ---
    (
        "Stock Entry Detail",
        "custom_billed_in_quotation",
        {
            "label": "Billed In Quotation",
            "fieldtype": "Link",
            "options": "Quotation",
            "insert_after": "basic_rate",
            "read_only": 1,
            "hidden": 1,
            "no_copy": 1,
            "description": "Set automatically when this STE line is included in a Quotation generated by the NMB HQ Monthly Billing report. Used to filter orphan STE rows that have already been billed.",
        },
    ),
    # --- Expense Claim (1 field — Phase 2 orphan support; header-level) ---
    (
        "Expense Claim",
        "custom_billed_in_quotation",
        {
            "label": "Billed In Quotation",
            "fieldtype": "Link",
            "options": "Quotation",
            "insert_after": "total_sanctioned_amount",
            "read_only": 1,
            "hidden": 1,
            "no_copy": 1,
            "description": "Set automatically when this Expense Claim is included in a Quotation generated by the NMB HQ Monthly Billing report. Field lives on header (claim-level), so once stamped, all detail lines disappear from the report.",
        },
    ),
]


def create_all():
    """Create all custom fields. Idempotent — skips fields that already exist."""
    created = []
    skipped = []
    errors = []

    for doctype, fieldname, props in FIELDS:
        try:
            existing = frappe.db.exists(
                "Custom Field", {"dt": doctype, "fieldname": fieldname}
            )
            if existing:
                skipped.append(f"{doctype}.{fieldname}")
                continue

            df = {"fieldname": fieldname, **props}
            create_custom_field(doctype, df)
            created.append(f"{doctype}.{fieldname}")
        except Exception as e:
            errors.append(f"{doctype}.{fieldname}: {e}")

    frappe.db.commit()

    print("=" * 60)
    print("NMB Billing — Custom Field Creation (3-field design)")
    print("=" * 60)
    print(f"Created: {len(created)}")
    for f in created:
        print(f"  + {f}")
    print(f"Already existed (skipped): {len(skipped)}")
    for f in skipped:
        print(f"  = {f}")
    if errors:
        print(f"Errors: {len(errors)}")
        for f in errors:
            print(f"  ! {f}")
    print("=" * 60)

    return {"created": created, "skipped": skipped, "errors": errors}


def remove_all():
    """Rollback — remove the 3 custom fields created by this script."""
    removed = []
    not_found = []
    for doctype, fieldname, _props in FIELDS:
        name = frappe.db.get_value(
            "Custom Field", {"dt": doctype, "fieldname": fieldname}, "name"
        )
        if name:
            frappe.delete_doc("Custom Field", name, force=1)
            removed.append(f"{doctype}.{fieldname}")
        else:
            not_found.append(f"{doctype}.{fieldname}")
    frappe.db.commit()
    print(f"Removed: {len(removed)}, Not found: {len(not_found)}")
    return {"removed": removed, "not_found": not_found}


def remove_legacy_fields():
    """Remove unused fields from the original 6-field design.
    Run ONCE if you previously created the old 6-field set."""
    LEGACY = [
        ("Material Request Item", "custom_unit_sell_price"),
        ("Material Request Item", "custom_pricing_comment"),
        ("Material Request Item", "custom_final_price"),
    ]
    removed = []
    not_found = []
    for doctype, fieldname in LEGACY:
        name = frappe.db.get_value(
            "Custom Field", {"dt": doctype, "fieldname": fieldname}, "name"
        )
        if name:
            frappe.delete_doc("Custom Field", name, force=1)
            removed.append(f"{doctype}.{fieldname}")
        else:
            not_found.append(f"{doctype}.{fieldname}")
    frappe.db.commit()
    print(f"Legacy cleanup: removed {len(removed)}, not_found {len(not_found)}")
    return {"removed": removed, "not_found": not_found}


if __name__ == "__main__":
    create_all()
