"""
NMB HQ Monthly Billing — Custom Field Creation Script
======================================================

Creates 6 custom fields needed by the monthly billing report.

Idempotent: safe to run multiple times. Existing fields are skipped.

USAGE:
    Run once via Frappe console:
        bench --site <your-site> console
        >>> exec(open('/path/to/create_billing_fields.py').read())

    Or via bench execute:
        bench --site <your-site> execute create_billing_fields.create_all

ROLLBACK:
    To remove all fields created by this script:
        bench --site <your-site> execute create_billing_fields.remove_all
"""

import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_field


# Fields are defined as (doctype, fieldname, properties) tuples
FIELDS = [
    # --- Material Request Item ---
    (
        "Material Request Item",
        "custom_unit_sell_price",
        {
            "label": "Unit Sell Price",
            "fieldtype": "Currency",
            "options": "TZS",
            "insert_after": "rate",
            "read_only": 1,
            "description": "Reference price: contract price if item is in Contract Price List, else cost / 0.80 (true 20% margin from market price). Computed by the monthly billing report.",
        },
    ),
    (
        "Material Request Item",
        "custom_pricing_comment",
        {
            "label": "Pricing Comment",
            "fieldtype": "Small Text",
            "insert_after": "custom_unit_sell_price",
            "read_only": 1,
            "description": "System-generated comment explaining the pricing decision (Contract OK / Below threshold / Not in contract / etc).",
        },
    ),
    (
        "Material Request Item",
        "custom_final_price",
        {
            "label": "Final Price",
            "fieldtype": "Currency",
            "options": "TZS",
            "insert_after": "custom_pricing_comment",
            "description": "Suggested selling price. Editable by the accountant — overrides system suggestion when generating Quotation.",
        },
    ),
    (
        "Material Request Item",
        "custom_quoted_in_qtn",
        {
            "label": "Quoted In",
            "fieldtype": "Link",
            "options": "Quotation",
            "insert_after": "custom_final_price",
            "read_only": 1,
            "description": "Set automatically when this MREQ line is included in a Quotation generated by the monthly billing report.",
        },
    ),
    # --- Quotation Item ---
    (
        "Quotation Item",
        "custom_approved_requisition_no",
        {
            "label": "Approved Requisition No.",
            "fieldtype": "Data",
            "insert_after": "item_name",
            "description": "NMB Purchase Requisition number — carried from the source MREQ for audit trail.",
        },
    ),
    (
        "Quotation Item",
        "custom_source_mreq_item",
        {
            "label": "Source MREQ Item",
            "fieldtype": "Data",
            "insert_after": "custom_approved_requisition_no",
            "read_only": 1,
            "description": "Reference back to the originating Material Request Item (format: MREQ-NNNNN / item-row-name).",
        },
    ),
]


def create_all():
    """Create all custom fields. Idempotent — skips fields that already exist."""
    created = []
    skipped = []
    errors = []

    for doctype, fieldname, props in FIELDS:
        try:
            existing = frappe.db.exists(
                "Custom Field", {"dt": doctype, "fieldname": fieldname}
            )
            if existing:
                skipped.append(f"{doctype}.{fieldname}")
                continue

            df = {"fieldname": fieldname, **props}
            create_custom_field(doctype, df)
            created.append(f"{doctype}.{fieldname}")
        except Exception as e:
            errors.append(f"{doctype}.{fieldname}: {e}")

    frappe.db.commit()

    print("=" * 60)
    print("NMB Billing — Custom Field Creation")
    print("=" * 60)
    print(f"Created: {len(created)}")
    for f in created:
        print(f"  + {f}")
    print(f"Already existed (skipped): {len(skipped)}")
    for f in skipped:
        print(f"  = {f}")
    if errors:
        print(f"Errors: {len(errors)}")
        for f in errors:
            print(f"  ! {f}")
    print("=" * 60)

    return {"created": created, "skipped": skipped, "errors": errors}


def remove_all():
    """Rollback — remove all custom fields created by this script.

    DANGER: deletes the fields and their data. Confirm before running.
    """
    removed = []
    not_found = []

    for doctype, fieldname, _props in FIELDS:
        name = frappe.db.get_value(
            "Custom Field", {"dt": doctype, "fieldname": fieldname}, "name"
        )
        if name:
            frappe.delete_doc("Custom Field", name, force=1)
            removed.append(f"{doctype}.{fieldname}")
        else:
            not_found.append(f"{doctype}.{fieldname}")

    frappe.db.commit()

    print("=" * 60)
    print("NMB Billing — Custom Field Rollback")
    print("=" * 60)
    print(f"Removed: {len(removed)}")
    for f in removed:
        print(f"  - {f}")
    print(f"Not found: {len(not_found)}")
    for f in not_found:
        print(f"  ? {f}")
    print("=" * 60)

    return {"removed": removed, "not_found": not_found}


if __name__ == "__main__":
    create_all()
